### ISSUE TITLE
Error extracing NEE data

### ISSUE THREAD

**Issue by djaiswal** [ropensci/smapr#56]
I was following instructions (https://cran.r-project.org/web/packages/smapr/vignettes/smapr-intro.html) to extract NEE data. 
However, I encountered an error when I extract after downloading data.

I got following error message

`> sm_raster <- extract_smap(local_files, '/NEE/nee_mean/')
Error in matrix == fill_value : non-conformable arrays
In addition: Warning message:
In H5Aread(A) :
  Reading attribute data of type 'VLEN' not yet implemented. Values replaced by NA's.
`

**Comment by mbjoseph** [comment]
Thanks @djaiswal for opening this issue! I had never tested smapr with the NEE data products, but I tracked down the error and it was due to differences in how the NA or fill values were stored in these data. 

This should be fixed now for the development version of smapr with #57, which you can install from GitHub via:

```
# install.packages("devtools")
devtools::install_github("ropensci/smapr")
```
